FROM node:20-slim

WORKDIR /app

COPY package*.json ./
COPY tsconfig.base.json ./

COPY apps/api/package*.json ./apps/api/

RUN npm install

COPY apps/api ./apps/api

WORKDIR /app/apps/api

RUN npm run build

EXPOSE 3001

CMD npm run db:migrate && node dist/server.js

